import os
import sys
import base64

def clean_key_and_pass():
    raw_key = os.environ.get("RAW_KEY", "")
    raw_pass = os.environ.get("RAW_PASS", "")

    # Clean password by stripping newlines/carriage returns
    clean_pass = raw_pass.strip("\r\n")

    # Inspect and clean raw_key
    # Check if the raw_key is a single-line base64 encoded string
    key_lines = [line.strip() for line in raw_key.splitlines() if line.strip()]
    
    actual_key_content = raw_key
    
    if len(key_lines) == 1:
        # It's a single line. Let's check if it is base64 encoded
        single_line = key_lines[0]
        if not single_line.startswith("untrusted comment"):
            try:
                decoded = base64.b64decode(single_line)
                if decoded.startswith(b"untrusted comment"):
                    print("Auto-detected base64-encoded private key. Decoding it...")
                    actual_key_content = decoded.decode('utf-8', errors='ignore')
            except Exception as e:
                print(f"Attempted to base64 decode single-line key but failed: {e}")

    # Now parse the actual key content
    lines = [line for line in actual_key_content.splitlines() if line.strip()]
    if not lines:
        print("Error: The signing private key is empty.")
        sys.exit(1)

    # Reconstruct the minisign key:
    # Join all subsequent lines into one clean base64 data string
    data_lines = lines[1:]
    data = "".join(data_lines).replace("\r", "").replace("\n", "").replace(" ", "")

    # Force the comment line to be the standard "untrusted comment: minisign encrypted secret key"
    # to prevent parser failures when keys are generated by rsign-cli.
    comment = "untrusted comment: minisign encrypted secret key"
    clean_key = f"{comment}\n{data}"

    # Write key to a local file in the workspace as binary to prevent Windows CRLF conversions
    key_file_path = os.path.abspath("signing.key")
    with open(key_file_path, "wb") as f:
        f.write(clean_key.encode("utf-8"))
    print(f"Successfully wrote signing key to: {key_file_path}")

    # Write to GITHUB_ENV
    github_env_path = os.environ.get("GITHUB_ENV")
    if github_env_path:
        with open(github_env_path, "a", encoding="utf-8") as f:
            f.write(f"TAURI_SIGNING_PRIVATE_KEY_PATH={key_file_path}\n")
            f.write(f"TAURI_SIGNING_PRIVATE_KEY_PASSWORD={clean_pass}\n")
        print("Successfully exported key path and password to GITHUB_ENV.")
    else:
        print("Error: GITHUB_ENV is not set.")
        sys.exit(1)

if __name__ == "__main__":
    clean_key_and_pass()
